##===- unittests/galaxy/Makefile -----------------------*- Makefile -*-===##
#
#                     The Galaxy Programming Language
#
# This file is distributed under the ISC License.
# See LICENSE.TXT for details.
#
##===------------------------------------------------------------------===##

LEVEL = ../..
TESTNAME = Galaxy
LINK_COMPONENTS := core
ExtraLibs = -lgalaxy

include $(LEVEL)/Makefile.common
include $(LEVEL)/unittests/Makefile.unittest
