##===- galaxy/tools/galaxyc/Makefile ------------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Stands for "Galaxy Compiler"
#
TOOLNAME=galaxyc

#
# List libraries that we'll need
#
USEDLIBS = galaxy.a galaxyast.a
LINK_COMPONENTS := support irreader

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
